const projects = [
  {
    id: "coffee-project",
    title: "Landing Page",
    summary: "A static landing page built to practice basic front-end layout and structure using HTML and CSS.",
    learnings: "Learned semantic HTML, Flexbox, and how to organize a simple layout. Also used Git for version control.",
    previewLink: "https://adnanetaleb10.github.io/odin-landing-page/",
    codeLink: "https://github.com/AdnaneTaleb10/odin-landing-page/tree/main",
  },
  {
    id: "tic-tac-toe-project",
    title: "Rock-Paper-Scissors",
    summary: "A simple browser game where users play Rock-Paper-Scissors against the computer using JavaScript.",
    learnings: "Practiced basic JavaScript, conditionals, and event listeners. Gained experience manipulating the DOM.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Rock-Paper-Scissors/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Rock-Paper-Scissors",
  },
  {
    id: "etch-sketch-project",
    title: "Etch-Sketch",
    summary: "A drawing app where users sketch on a grid and reset the canvas. Built using HTML, CSS, and JavaScript.",
    learnings: "Improved DOM handling, event listeners, and dynamic styling. Helped me get more comfortable with UI logic.",
    previewLink: "https://adnanetaleb10.github.io/odin-Etch-a-Sketch/",
    codeLink: "https://github.com/AdnaneTaleb10/odin-Etch-a-Sketch",
  },
  {
    id: "calculator-project",
    title: "Calculator",
    summary: "A basic calculator that handles simple arithmetic operations, built with vanilla JavaScript.",
    learnings: "Reinforced JavaScript functions and how to update the UI based on user input. Helped me with small app structure.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Calculator/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Calculator?tab=readme-ov-file",
  },
  {
    id: "signup-project",
    title: "Sign-up Form",
    summary: "A form built with HTML and CSS to practice user input validation and styling.",
    learnings: "Gained experience using form validation and styling layouts. Focused on building a clean and usable design.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Sign-up-Form/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Sign-up-Form",
  },
  {
    id: "library-project",
    title: "Library App",
    summary: "A basic app to add and manage books. Users can mark books as read or unread and delete them.",
    learnings: "Practiced JavaScript CRUD operations, DOM manipulation, and built a simple responsive layout using Flexbox.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Library/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Library",
  },
  {
    id: "restaurant-project",
    title: "Restaurant App",
    summary: "A basic multi-page restaurant site built using HTML, CSS, and JavaScript with Webpack setup.",
    learnings: "Practiced organizing a small site with Webpack and npm. Improved my understanding of modular code structure.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Restaurant-Page/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Restaurant-Page",
  },
  {
    id: "to-do-list-project",
    title: "To-Do List App",
    summary: "A task manager app to create, update, and organize tasks with due dates and priorities.",
    learnings: "Learned modular JavaScript, LocalStorage, and object-oriented patterns. Practiced structuring medium apps.",
    previewLink: "https://adnanetaleb10.github.io/Odin-To-Do-List/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-To-Do-List",
  },
  {
    id: "weather-project",
    title: "Weather App",
    summary: "A weather app where users can search cities and view forecasts using a third-party API.",
    learnings: "Practiced using async/await and APIs. Helped me learn how to display real-time data in a clean UI.",
    previewLink: "https://adnanetaleb10.github.io/Odin-Weather-App/",
    codeLink: "https://github.com/AdnaneTaleb10/Odin-Weather-App",
  },
];


export { projects };
